// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAutoSwitch():Promise<boolean>;

export function GetAutostartEnabled():Promise<boolean>;

export function GetInputDevices():Promise<Array<main.AudioDeviceInfo>>;

export function GetLockVolume():Promise<boolean>;

export function GetOutputDevices():Promise<Array<main.AudioDeviceInfo>>;

export function GetVolumes():Promise<main.VolumeInfo>;

export function HasUnsavedChanges():Promise<boolean>;

export function HideWindow():Promise<void>;

export function MarkAutostartAsked():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function ResetChanges():Promise<void>;

export function SaveSettings():Promise<void>;

export function SelectInputDevice(arg1:string):Promise<void>;

export function SelectOutputDevice(arg1:string):Promise<void>;

export function SetAutoSwitch(arg1:boolean):Promise<void>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function SetInputVolume(arg1:number):Promise<void>;

export function SetLockVolume(arg1:boolean):Promise<void>;

export function SetOutputVolume(arg1:number):Promise<void>;

export function ShouldShowAutostartPrompt():Promise<boolean>;

export function ShowWindow():Promise<void>;
