// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoSwitch() {
  return window['go']['main']['App']['GetAutoSwitch']();
}

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function GetLockVolume() {
  return window['go']['main']['App']['GetLockVolume']();
}

export function GetOutputDevices() {
  return window['go']['main']['App']['GetOutputDevices']();
}

export function GetVolumes() {
  return window['go']['main']['App']['GetVolumes']();
}

export function HasUnsavedChanges() {
  return window['go']['main']['App']['HasUnsavedChanges']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function MarkAutostartAsked() {
  return window['go']['main']['App']['MarkAutostartAsked']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetChanges() {
  return window['go']['main']['App']['ResetChanges']();
}

export function SaveSettings() {
  return window['go']['main']['App']['SaveSettings']();
}

export function SelectInputDevice(arg1) {
  return window['go']['main']['App']['SelectInputDevice'](arg1);
}

export function SelectOutputDevice(arg1) {
  return window['go']['main']['App']['SelectOutputDevice'](arg1);
}

export function SetAutoSwitch(arg1) {
  return window['go']['main']['App']['SetAutoSwitch'](arg1);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetInputVolume(arg1) {
  return window['go']['main']['App']['SetInputVolume'](arg1);
}

export function SetLockVolume(arg1) {
  return window['go']['main']['App']['SetLockVolume'](arg1);
}

export function SetOutputVolume(arg1) {
  return window['go']['main']['App']['SetOutputVolume'](arg1);
}

export function ShouldShowAutostartPrompt() {
  return window['go']['main']['App']['ShouldShowAutostartPrompt']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
